# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['file_refresher.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config.yaml', '.'),
        ('icon.ico', '.'),
    ],
    hiddenimports=[
        'rich.console',
        'rich.progress',
        'rich.panel',
        'rich.table',
        'rich.text',
        'rich.align',
        'rich.layout',
        'yaml',
        'csv',
        'pathlib',
        'datetime',
        'logging',
        're',
        'argparse',
        'os',
        'sys',
        'time',
        'collections',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'IPython',
        'jupyter',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='file_refresher',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icon.ico'
)